;BatteryStatus.ini

[Settings]
alert1pct=50
alert2pct=25
alert3pct=12
alert1ms=8000
alert2ms=8000
alert3ms=800000
ImgPath=%A_ScriptDir%
alert1img=%ImgPath%\ClipartConnection_3700840.thm.jpg
alert2img=%ImgPath%\ClipartConnection_3775471_thm.jpg
alert3img=%ImgPath%\ClipartConnection_3775475_thm.jpg
alert1cmd=%windir%\media\notify.wav
alert2cmd=%windir%\media\notify.wav
alert3cmd=%windir%\media\notify.wav
UNPLUGms=7000
UNPLUGimg=%ImgPath%\ClipartConnection_3890038_thm.jpg
UNPLUGcmd=%windir%\media\notify.wav
PLUGINms=7000
PLUGINimg=%ImgPath%\ClipartConnection_3861328_thm.jpg
PLUGINcmd=%windir%\media\notify.wav
FULLms=7000
FULLimg=%ImgPath%\ClipartConnection_3775464_thm.jpg
FULLcmd=%windir%\media\notify.wav
pollingms=8000
